# =======================================
# Configuration File Template for AstroKit package
# Author: Rui Zhu
# =======================================

# software directory
PATH_SEX:  # SExtractor program file directory
  /opt/homebrew/Cellar/sextractor/2.28.0/share/sextractor
PATH_EAZY:  # EAZY program file directory
  /Users/rui/Applications/eazy-photoz

# Quick Directory
DIR_DOWNLOAD:  # Default save file path
  /Users/rui/Downloads
DIR_DATA:  # Database in this equipment
  /Users/rui/Data