"""
A Python Interface for nway command line version.

- Author: Rui Zhu
- Date: 2025-12-01
"""
from pathlib import Path
from astropy.io import fits
from loguru import logger
import shutil
import time
import subprocess

from astrokit.toolbox import sec_to_hms

__all__ = ["Nway"]

class Nway:
    def __init__(
            self, 
            input_catalogs: list[Path],
            output_catalog: Path, 
    ):
        self.input_catalogs = [Path(p) for p in input_catalogs]
        self.output_catalog = output_catalog
    
    def set_skyarea(self, path, ext_name, skyarea):
        """
        Set the SKYAREA keyword in the header of the specified extension.
        
        NOTE: This will modify the input catalog file in place.

        Parameters
        ----------
        path : Path
            path to the catalog FITS file needing to set SKYAREA.
        ext_name : str
            extension name where to set the SKYAREA keyword.
        skyarea : float
            sky area value to set in square degrees.
        """
        path = Path(path)
        with fits.open(path, mode='update') as hdul:
            hdr = hdul[ext_name].header
            hdr['SKYAREA'] = skyarea
            hdul.flush()
    
    def _input_catalog_check(self, path):
        path = Path(path)
        if not path.exists():
            raise FileNotFoundError(f"Input catalog {path} does not exist.")
        if not path.suffix.lower() in [".fits", ".fit"]:
            raise ValueError(f"Input catalog {path.name} is not a FITS file.")
        # check the keyword SKYAREA in the header
        header = fits.getheader(path, ext=1)
        if 'SKYAREA' not in header:
            raise ValueError(f"Input catalog {path.name} does not have SKYAREA keyword in the header.")
    
    def match(
            self, pos_err, radius, priors=None, 
            mag_radius=None, mag_exclud_radius=None, mag_auto_minprob=None, 
            prior_completeness=None, acceptable_prob=None, 
            min_prob=None, ignore_unrelated_associations=None, 
            prefilter_pair=None
            ):
        """
        Run nway in the command line mode to perform cross-matching.
        """
        # check input catalogs
        for path in self.input_catalogs:
            self._input_catalog_check(path)
        
        # construct the nway command
        dir_work = self.input_catalogs[0].parent
        logger.info(f"Working directory: {dir_work}")
        st = time.time()

        n_cat = len(self.input_catalogs)
        cmd = f"nway.py "
        for i in range(n_cat):
            if isinstance(pos_err[i], str):
                cmd += f"{self.input_catalogs[i].name} :{pos_err[i]} "
            else:
                cmd += f"{self.input_catalogs[i].name} {pos_err[i]} "
        cmd += f"--out={self.output_catalog.name} "
        if radius is not None:
            cmd += f"--radius {radius} "
        if priors is not None:
            for prior in priors:
                cmd += f"--mag {prior[0]}:{prior[1]} {prior[2]} "
        if mag_radius is not None:
            cmd += f"--mag-radius {mag_radius} "
        if mag_exclud_radius is not None:
            cmd += f"--mag-exclud-radius {mag_exclud_radius} "
        if mag_auto_minprob is not None:
            cmd += f"--mag-auto-minprob {mag_auto_minprob} "
        if prior_completeness is not None:
            cmd += f"--prior-completeness {prior_completeness} "
        if acceptable_prob is not None:
            cmd += f"--acceptable-prob {acceptable_prob} "
        if min_prob is not None:
            cmd += f"--min-prob {min_prob} "
        if ignore_unrelated_associations is not None:
            cmd += f"--ignore-unrelated-associations {ignore_unrelated_associations} "
        if prefilter_pair is not None:
            cmd += f"--prefilter-pair {prefilter_pair} "
        
        # execute the command in the working directory
        process = subprocess.run(
            args=cmd, 
            cwd=dir_work,
            stdout=None,
            stderr=None,
            universal_newlines=True,
            shell=True
        )
        # remove the cache files generated by nway
        dir_cache = dir_work / "cache"
        shutil.rmtree(dir_cache)
        logger.info("The cache files have been removed.")

        logger.info(f"nway matching completed in {sec_to_hms(time.time() - st)}.")
        
        return cmd